### ISSUE TITLE
Add twitter links along with the website info on people to follow section.

### ISSUE THREAD

**Issue by shirazz** [fayausa/techmyrmidons-web#5]
Adding the twitter links might be helpful in getting quick updates.

**Comment by deepusnath** [comment]
Thank you for the suggestion. As of now, we are just linking photos in people to follow section directly to their Twitter profile or website. We can add a section below the pic to show icons of different resources so that people will be profiled better. 

We are revamping the website to make it easy to manage the entire content on the site in the related Json files. Will let you know once the new site gets available.

**Comment by shirazz** [comment]
Cool!! That’s would be awesome..

**Comment by deepusnath** [comment]
Revamped website is up and running.

**Comment by rejahrehim** [comment]
Fixed in the latest release. Closing
